(in-package #:verona.backend.llvm)

(defun emit-primitive (backend expression)
  (let* ((operation (verona:primitive-call-operation expression))
         (kind (verona:primitive-operation-kind operation))
         (arguments (mapcar (lambda (argument) (emit-value backend argument))
                            (verona:semantic-call-arguments expression)))
         (result-type (lower-type backend (verona:expression-type expression)))
         (builder (llvm-backend-builder backend)))
    (flet ((binary (function)
             (funcall function builder (first arguments) (second arguments) "result"))
           (compare (predicate)
             (llvm:build-i-cmp builder predicate (first arguments) (second arguments) "result"))
           (float-compare (predicate)
             (llvm:build-f-cmp builder predicate (first arguments) (second arguments) "result"))
           (cast (function)
             (funcall function builder (first arguments) result-type "result")))
      (case kind
        (:integer-add (binary #'llvm:build-add))
        (:integer-subtract (binary #'llvm:build-sub))
        (:integer-multiply (binary #'llvm:build-mul))
        (:signed-integer-divide (binary #'llvm:build-s-div))
        (:unsigned-integer-divide (binary #'llvm:build-u-div))
        (:float-add (binary #'llvm:build-f-add))
        (:float-subtract (binary #'llvm:build-f-sub))
        (:float-multiply (binary #'llvm:build-f-mul))
        (:float-divide (binary #'llvm:build-f-div))
        (:boolean-not (llvm:build-not builder (first arguments) "result"))
        (:boolean-and (binary #'llvm:build-and))
        (:boolean-or (binary #'llvm:build-or))
        (:boolean-equal (compare :=))
        (:boolean-not-equal (compare :/=))
        (:pointer-equal (compare :=))
        (:pointer-not-equal (compare :/=))
        (:signed-integer-equal (compare :=))
        (:unsigned-integer-equal (compare :=))
        (:signed-integer-not-equal (compare :/=))
        (:unsigned-integer-not-equal (compare :/=))
        (:signed-integer-less-than (compare :<))
        (:signed-integer-less-than-or-equal (compare :<=))
        (:signed-integer-greater-than (compare :>))
        (:signed-integer-greater-than-or-equal (compare :>=))
        (:unsigned-integer-less-than (compare :unsigned-<))
        (:unsigned-integer-less-than-or-equal (compare :unsigned-<=))
        (:unsigned-integer-greater-than (compare :unsigned->))
        (:unsigned-integer-greater-than-or-equal (compare :unsigned->=))
        (:float-ordered-equal (float-compare :=))
        (:float-ordered-not-equal (float-compare :/=))
        (:float-ordered-less-than (float-compare :<))
        (:float-ordered-less-than-or-equal (float-compare :<=))
		(:float-ordered-greater-than (float-compare :>))
		(:float-ordered-greater-than-or-equal (float-compare :>=))
		;; Signedness affects Verona's type system but not an LLVM integer's
		;; representation.  A same-width signed/unsigned conversion therefore
		;; emits no instruction and simply preserves the SSA value.
		(:integer-reinterpret (first arguments))
		(:integer-sign-extend (cast #'llvm:build-s-ext))
        (:integer-zero-extend (cast #'llvm:build-z-ext))
        (:integer-truncate (cast #'llvm:build-trunc))
        (:signed-integer-to-float (cast #'llvm:build-si-to-fp))
        (:unsigned-integer-to-float (cast #'llvm:build-ui-to-fp))
        (:float-to-signed-integer (cast #'llvm:build-fp-to-si))
        (:float-to-unsigned-integer (cast #'llvm:build-fp-to-ui))
        (:float-extend (cast #'llvm:build-fp-ext))
        (:float-truncate (cast #'llvm:build-fp-trunc))
        (otherwise
         (backend-fail "PrimitiveOperation kind ~S is not implemented" kind))))))
