(defpackage #:verona
  (:use #:cl)
  (:shadow #:compile-file #:declaration #:import)
  (:export
   #:compiler
   #:make-compiler
   #:compiler-phase-timing-p
   #:compiler-phase-timings
   #:clear-compiler-phase-timings
   #:source
   #:make-source
   #:source-from-file
   #:source-name
   #:source-contents
   #:source-location
   #:source-location-source
   #:source-location-offset
   #:source-location-line
   #:source-location-column
   #:source-range
   #:make-source-range
   #:source-range-start
   #:source-range-end
   #:syntax-source-range
   #:diagnostic
   #:make-diagnostic
   #:diagnostic-severity
   #:diagnostic-code
   #:diagnostic-message
   #:diagnostic-primary-location
   #:diagnostic-secondary-locations
   #:diagnostic-notes
   #:diagnostic-data
   #:+error-severity+
   #:+warning-severity+
   #:diagnostic-code-for
   #:condition-primary-range
   #:diagnostic-for-condition
   #:render-diagnostic
   #:user-compilation-error
   #:condition-diagnostic
   #:compiler-bug
   #:compiler-bug-message
   #:compiler-bug-context
   #:compiler-assert
   #:syntax
   #:make-syntax
   #:syntax-datum
   #:syntax-source
   #:syntax-start
   #:syntax-end
   #:syntax-expansion-origin
   #:syntax-with-datum
   #:verona-name
   #:make-verona-name
   #:verona-name-p
   #:verona-name-value
   #:verona-name=
   #:module-name
   #:make-module-name
   #:module-name-p
   #:module-name-components
   #:module-name=
   #:module-name-string
   #:qualified-name
   #:make-qualified-name
   #:qualified-name-p
   #:qualified-name-qualifier
   #:qualified-name-name
   #:qualified-name-string
   #:verona-symbol
   #:verona-symbol-name
   #:unit-literal
   #:unit-literal-p
   #:verona-boolean-literal
   #:verona-boolean-literal-p
   #:verona-boolean-literal-value
   #:verona-list
   #:make-verona-list
   #:verona-list-p
   #:verona-list-elements
   #:verona-callable
   #:verona-callable-p
   #:verona-function
   #:make-verona-function
   #:verona-function-p
   #:verona-macro
   #:make-verona-macro
   #:verona-macro-p
   #:verona-macro-source
   #:expansion-origin
   #:make-expansion-origin
   #:expansion-origin-invocation
   #:expansion-origin-macro
   #:expansion-origin-parent-origin
   #:environment
   #:make-environment
   #:environment-parent
   #:environment-bind
   #:environment-lookup
   #:environment-child
   #:unbound-name-error
   #:unbound-name-error-name
   #:not-callable-error
   #:not-callable-error-value
   #:evaluate
   #:expand
   #:macro-expansion-limit-error
   #:macro-expansion-limit-error-limit
   #:macro-expansion-limit-error-syntax
   #:*macro-expansion-depth-limit*
   #:make-bootstrap-environment
   #:read-source
   #:target-feature-names
   #:*reader-nesting-depth-limit*
   #:compilation-unit
   #:compilation-unit-source
   #:compilation-unit-forms
   #:compilation-unit-declarations
   #:compilation-unit-namespace
   #:compilation-unit-environment
   #:compilation-unit-compile-time-environment
   #:compilation-unit-semantic-program
   #:module
   #:module-name
   #:module-pathname
   #:module-identity-explicit-p
   #:module-imports
   #:module-exports
   #:module-native-export-specs
   #:native-export-spec
   #:native-export-spec-name
   #:native-export-spec-external-name
   #:native-export-spec-source
   #:module-find-export
   #:import
   #:import-module
   #:import-alias
   #:module-loader
   #:module-loader-search-paths
   #:module-loader-features
   #:module-loader-loaded-modules
   #:module-loader-load
   #:module-graph
   #:module-graph-modules
   #:module-graph-edges
   #:module-source
   #:module-forms
   #:module-declarations
   #:module-namespace
   #:module-environment
   #:module-lookup
   #:unit-declarations
   #:find-declaration
   #:register-declaration
   #:declaration
   #:semantic-binding
   #:semantic-binding-name
   #:declaration-name
   #:declaration-source
   #:declaration-expanded-syntax
   #:declaration-module
   #:declaration-compilation-unit
   #:declaration-documentation
   #:declaration-documentation-syntax
   #:declaration-type-declaration
   #:type-declaration
   #:type-declaration-kind
   #:type-declaration-body
   #:type-alias-declaration
   #:type-alias-declaration-target
   #:function-declaration
   #:function-declaration-for-clause
   #:function-declaration-parameters
   #:function-declaration-return-type
   #:function-declaration-body
   #:external-function-declaration
   #:external-function-declaration-external-name
   #:external-function-declaration-parameter-types
   #:external-function-declaration-result-type
   #:macro-declaration
   #:macro-declaration-parameters
   #:macro-declaration-body
   #:constant-declaration
   #:constant-declaration-type
   #:constant-declaration-value
   #:variable-declaration
   #:variable-declaration-type
   #:variable-declaration-initializer
   #:generic-declaration
   #:generic-declaration-parameters
   #:generic-declaration-arity
   #:implementation-declaration
   #:implementation-declaration-generic-name
   #:implementation-declaration-parameters
   #:implementation-declaration-return-type
   #:implementation-declaration-body
   #:implementation-declaration-protocol-application
   #:implementation-declaration-operations
   #:protocol-declaration
   #:protocol-declaration-parameters
   #:protocol-declaration-operations
   #:semantic-scope
   #:make-semantic-scope
   #:semantic-scope-parent
   #:semantic-scope-bind
   #:semantic-scope-find
   #:semantic-scope-lookup
   #:semantic-scope-child
   #:semantic-scope-owning-program
   #:semantic-scope-owning-type-context
   #:semantic-scope-function
   #:semantic-scope-owning-function
   #:semantic-program
   #:semantic-program-bootstrap-scope
   #:semantic-program-module-scope
   #:semantic-program-declarations
   #:semantic-program-declaration
   #:semantic-program-type-context
   #:program
   #:program-entry-module
   #:program-modules
   #:program-module-graph
   #:program-target
   #:semantic-program-native-exports
   #:semantic-program-function-specializations
   #:native-export-binding
   #:native-export-binding-function
   #:native-export-binding-external-name
   #:compile-source
   #:read-verona
   #:macroexpand-verona
   #:analyze-verona
   #:typecheck-verona
   #:semantic-program-module-scope-for
   #:make-bootstrap-semantic-scope
   #:parameter-binding
   #:parameter-binding-syntax
   #:parameter-binding-type-syntax
   #:parameter-binding-type-reference
   #:parameter-binding-type
   #:pattern-binding
   #:pattern-binding-syntax
   #:pattern-binding-type
   #:let-binding
   #:let-binding-syntax
   #:let-binding-source
   #:let-binding-type-syntax
   #:let-binding-type-reference
   #:let-binding-type
   #:let-binding-initializer
   #:semantic-declaration
   #:semantic-declaration-source-declaration
   #:semantic-type-declaration
   #:semantic-type-declaration-type
   #:semantic-type-declaration-fields
   #:semantic-type-alias-declaration
   #:semantic-type-alias-declaration-target-reference
   #:semantic-type-alias-declaration-target-type
   #:type-alias-binding
   #:type-alias-binding-type
   #:semantic-constant-declaration
   #:semantic-constant-declaration-type-reference
   #:semantic-constant-declaration-type
   #:semantic-constant-declaration-initializer
   #:semantic-variable-declaration
   #:semantic-variable-declaration-type-reference
   #:semantic-variable-declaration-type
   #:semantic-variable-declaration-initializer
   #:semantic-function-declaration
   #:semantic-function-declaration-scope
   #:semantic-function-declaration-type-parameters
   #:semantic-function-declaration-constraints
   #:semantic-function-declaration-parameters
   #:semantic-function-declaration-return-type-reference
   #:semantic-function-declaration-return-type
   #:semantic-function-declaration-type
   #:semantic-function-declaration-body
   #:semantic-function-specialization
   #:semantic-function-specialization-template
   #:semantic-function-specialization-type-arguments
   #:semantic-function-specialization-resolving-p
   #:semantic-protocol-declaration
   #:semantic-protocol-declaration-protocol
   #:semantic-protocol-implementation
   #:semantic-protocol-implementation-implementation
   #:semantic-protocol-operation-implementation
   #:semantic-protocol-operation-implementation-implementation
   #:semantic-protocol-operation-implementation-operation
   #:semantic-external-function-declaration
   #:semantic-external-function-declaration-external-name
   #:semantic-external-function-declaration-parameter-type-references
   #:semantic-external-function-declaration-parameter-types
   #:semantic-external-function-declaration-result-type-reference
   #:semantic-external-function-declaration-result-type
   #:semantic-external-function-declaration-type
   #:semantic-generic-declaration
   #:semantic-generic-declaration-generic
   #:semantic-generic-implementation
   #:semantic-generic-implementation-scope
   #:semantic-generic-implementation-return-type-reference
   #:semantic-generic-implementation-type
   #:generic
   #:generic-declaration
   #:generic-name
   #:generic-arity
   #:generic-implementations
   #:generic-binding
   #:generic-binding-generic
   #:generic-implementation
   #:generic-implementation-declaration
   #:generic-implementation-generic
   #:generic-implementation-parameters
   #:generic-implementation-parameter-types
   #:generic-implementation-result-type
   #:generic-implementation-body
   #:generic-implementation-primitive-operation
   #:generic-find-implementation
   #:semantic-expression
   #:semantic-expression-syntax
   #:semantic-expression-type
   #:expression
   #:expression-syntax
   #:expression-source
   #:expression-type
   #:semantic-literal
   #:unit-expression

   #:unit-expression-value
   #:unit-value
   #:boolean-literal
   #:boolean-literal-value
   #:character-literal
   #:character-literal-value
   #:integer-literal
   #:integer-literal-value
   #:float-literal
   #:float-literal-value
   #:string-literal
   #:string-literal-value
   #:semantic-reference
   #:semantic-reference-name
   #:semantic-reference-binding
   #:reference-expression
   #:semantic-call
   #:semantic-call-callee
   #:semantic-call-arguments
   #:polymorphic-call
   #:polymorphic-call-function
   #:polymorphic-call-substitution
   #:protocol-operation-call
   #:protocol-operation-call-operation
   #:protocol-operation-call-constraint
   #:external-call-expression
   #:external-call-expression-external-function
   #:call-expression
   #:primitive-call
   #:primitive-call-operation
   #:conversion-expression
   #:pointer-cast-expression
   #:pointer-cast-expression-operand
   #:pointer-offset-expression
   #:pointer-offset-expression-pointer
   #:pointer-offset-expression-offset
   #:function-pointer-expression
   #:function-pointer-expression-operand
   #:construct-expression
   #:construct-expression-product-type
   #:construct-expression-fields
   #:sum-construct-expression
   #:sum-construct-expression-alternative
   #:sum-construct-expression-arguments
   #:array-construct-expression
   #:array-construct-expression-elements
   #:index-expression
   #:index-expression-base
   #:index-expression-index
   #:index-expression-element-type
   #:index-place
   #:field-expression
   #:field-expression-value
   #:field-expression-field
   #:sequence-expression
   #:sequence-expression-expressions
   #:let-expression
   #:let-expression-bindings
   #:let-expression-scope
   #:let-expression-body
   #:address-expression
   #:address-expression-operand
   #:dereference-expression
   #:dereference-expression-operand
   #:load-expression
   #:load-expression-place
   #:assignment-expression
   #:assignment-expression-target
   #:assignment-expression-value
   #:store-expression
   #:return-expression
   #:return-expression-value
   #:pattern
   #:pattern-syntax
   #:pattern-type
   #:literal-pattern
   #:literal-pattern-value
   #:boolean-pattern
   #:character-pattern
   #:integer-pattern
   #:wildcard-pattern
   #:binding-pattern
   #:binding-pattern-binding
   #:constructor-pattern
   #:constructor-pattern-alternative
   #:constructor-pattern-payload-patterns
   #:match-case
   #:match-case-syntax
   #:match-case-pattern
   #:match-case-scope
   #:match-case-expression
   #:match-expression
   #:match-expression-value
   #:match-expression-cases
   #:place-expression
   #:place-expression-addressable-p
   #:place-expression-writable-p
   #:semantic-type-syntax
   #:semantic-unit-type-syntax
   #:semantic-pointer-type-syntax
   #:semantic-pointer-type-syntax-target
   #:semantic-array-type-syntax
   #:semantic-array-type-syntax-element-type
   #:semantic-array-type-syntax-length
   #:semantic-function-type-syntax
   #:semantic-function-type-syntax-parameters
   #:semantic-function-type-syntax-result
   #:verona-type
   #:type-parameter
   #:type-parameter-declaration
   #:type-parameter-index
   #:type-parameter-source
   #:type-substitution
   #:make-type-substitution
   #:type-substitution-entries
   #:type-substitution-find
   #:type-substitution-bind
   #:apply-type-substitution
   #:unify-types
   #:for-clause
   #:for-clause-syntax
   #:for-clause-type-parameters
   #:for-clause-constraint-syntaxes
   #:protocol
   #:protocol-declaration
   #:protocol-name
   #:protocol-type-parameters
   #:protocol-operations
   #:protocol-implementations
   #:protocol-binding
   #:protocol-binding-protocol
   #:protocol-operation
   #:protocol-operation-protocol
   #:protocol-operation-name
   #:protocol-operation-parameters
   #:protocol-operation-result-type
   #:protocol-operation-source
   #:protocol-constraint
   #:protocol-constraint-protocol
   #:protocol-constraint-arguments
   #:protocol-constraint-source
   #:protocol-implementation
   #:protocol-implementation-protocol
   #:protocol-implementation-arguments
   #:protocol-implementation-operations
   #:protocol-implementation-source
   #:protocol-implementation-find-operation
   #:protocol-find-implementation
   #:unit-type
   #:void-type
   #:never-type
   #:boolean-type
   #:char-type
   #:integer-type
   #:integer-type-signed
   #:integer-type-width
   #:float-type
   #:float-type-width
   #:pointer-type
   #:pointer-type-target
   #:pointer-type-pointee
   #:array-type
   #:array-type-element-type
   #:array-type-length
   #:function-type
   #:function-type-parameters
   #:function-type-result
   #:defined-type
   #:defined-type-declaration
   #:opaque-type
   #:product-type
   #:product-type-fields
   #:product-type-find-field
   #:product-field
   #:product-field-name
   #:product-field-type
   #:product-field-index
   #:product-field-source
   #:sum-type
   #:sum-type-alternatives
   #:sum-type-find-alternative
   #:sum-alternative
   #:sum-alternative-sum-type
   #:sum-alternative-name
   #:sum-alternative-index
   #:sum-alternative-payload-types
   #:sum-alternative-source
   #:type-context
   #:make-type-context
   #:type-context-unit-type
   #:type-context-void-type
   #:type-context-never-type
   #:type-context-unit-value
   #:type-context-pointer-width
   #:type-context-unit-representation-type
   #:unit-machine-representation
   #:type-context-boolean-type
   #:type-context-char-type
   #:type-context-c-int-type
   #:type-context-integer-type
   #:type-context-float-type
   #:type-context-pointer-type
   #:type-context-array-type
   #:type-context-function-type
   #:type-context-defined-type
   #:type-context-opaque-type
   #:type-context-product-type
   #:type-context-sum-type
   #:builtin-type-binding
   #:builtin-type-binding-type
   #:builtin-type-declaration
   #:builtin-intrinsic-binding
   #:builtin-intrinsic-binding-type
   #:primitive-binding
   #:primitive-binding-operation
   #:primitive-operation
   #:primitive-operation-identity
   #:primitive-operation-name
   #:primitive-operation-parameter-types
   #:primitive-operation-result-type
   #:primitive-operation-kind
   #:primitive-operation-nan-semantics
   #:expected-type-error
   #:unknown-type-error
   #:unknown-type-error-name
   #:expected-type-error-binding
   #:resolve-type
   #:resolve-types
   #:infer-expression
   #:check-expression
   #:same-type-p
   #:compatible-p
   #:type-mismatch-error
   #:type-mismatch-error-actual
   #:type-mismatch-error-expected
   #:cannot-infer-array-element-type-error
   #:array-element-type-mismatch-error
   #:array-index-out-of-bounds-error
   #:generic-arity-mismatch-error
   #:generic-arity-mismatch-error-generic
   #:generic-arity-mismatch-error-actual
   #:duplicate-type-parameter-error
   #:unknown-protocol-error
   #:protocol-arity-mismatch-error
   #:invalid-protocol-constraint-error
   #:cannot-infer-type-parameter-error
   #:conflicting-type-inference-error
   #:recursive-specialization-error
   #:duplicate-generic-implementation-error
   #:duplicate-generic-implementation-error-generic
   #:duplicate-generic-implementation-error-parameter-types
   #:duplicate-generic-implementation-error-original
   #:duplicate-generic-implementation-error-duplicate
   #:duplicate-generic-implementation-error-original-source
   #:duplicate-generic-implementation-error-duplicate-source
   #:no-generic-implementation-error
   #:no-generic-implementation-error-generic
   #:no-generic-implementation-error-argument-types
   #:semantic-not-callable-error
   #:wrong-argument-count-error
   #:wrong-argument-count-error-expected
   #:wrong-argument-count-error-actual
   #:duplicate-field-error
   #:duplicate-field-error-name
   #:duplicate-field-error-existing
   #:duplicate-alternative-error
   #:duplicate-alternative-error-name
   #:duplicate-alternative-error-existing
   #:recursive-type-not-supported-error
   #:type-alias-cycle-error
   #:unknown-field-error
   #:unknown-field-error-product-type
   #:unknown-field-error-name
   #:field-access-requires-product-error
   #:field-access-requires-product-error-actual
   #:not-addressable-error
   #:not-writable-error
   #:invalid-expression-error
   #:non-exhaustive-match-error
   #:non-exhaustive-match-error-uncovered
   #:unreachable-pattern-error
   #:unreachable-pattern-error-covering-pattern
   #:unreachable-expression-error
   #:return-outside-function-error
   #:backend-validation-error
   #:validate-for-backend
   #:backend-representable-type-p
   #:verona-type-name
   #:build-semantic-expression
   #:resolve-compilation-unit
   #:resolve-program
   #:definition-form-p
   #:make-primitive-definition
   #:process-definition
   #:expand-top-level
   #:top-level-expansion-result
   #:make-top-level-expansion-result
   #:top-level-expansion-result-definitions
   #:definition-error
   #:definition-error-syntax
   #:duplicate-declaration-error
   #:duplicate-declaration-error-name
   #:duplicate-declaration-error-existing
   #:non-definition-top-level-error
   #:semantic-error
   #:semantic-error-syntax
   #:invalid-native-export
   #:unresolved-name-error
   #:unresolved-name-error-name
   #:duplicate-local-binding-error
   #:invalid-definition-context-error
   #:compile-string
   #:compile-file
   #:compile-module
   #:compiler-search-paths
   #:module-error
   #:module-not-found
   #:duplicate-module
   #:circular-module-dependency
   #:circular-module-dependency-cycle
   #:duplicate-import-alias
   #:duplicate-import-alias-alias
   #:unknown-export
   #:unknown-export-name
   #:unknown-module-qualifier
   #:module-not-imported
   #:unknown-module-member
   #:private-declaration-access
   #:source-error
   #:verona-read-error
   #:verona-read-error-source
   #:verona-read-error-location))
